
# https://github.com/nodejs/docker-node/blob/main/README.md#how-to-use-this-image
#

services:
    nextjs-sample-app:
        image: node:22.9.0
        volumes:
            - ./app:/var/www/html
        ports:
            - 8080:3000
        tty: true
        working_dir: /var/www/html
        networks:
            - httpclient-checker-network
        environment:
            # https://nextjs.org/docs/messages/non-standard-node-env
            #
            - NODE_ENV=development
        command: "npm run dev"


networks:
    httpclient-checker-network:
        name: httpclient_checker_network
